// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: coursemanagement.proto

package course_management_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coursemanagement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_coursemanagement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_coursemanagement_proto_rawDescGZIP(), []int{0}
}

type SubjectItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price int32  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *SubjectItem) Reset() {
	*x = SubjectItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coursemanagement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectItem) ProtoMessage() {}

func (x *SubjectItem) ProtoReflect() protoreflect.Message {
	mi := &file_coursemanagement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectItem.ProtoReflect.Descriptor instead.
func (*SubjectItem) Descriptor() ([]byte, []int) {
	return file_coursemanagement_proto_rawDescGZIP(), []int{1}
}

func (x *SubjectItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubjectItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SubjectList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject []*SubjectItem `protobuf:"bytes,1,rep,name=subject,proto3" json:"subject,omitempty"`
}

func (x *SubjectList) Reset() {
	*x = SubjectList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coursemanagement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectList) ProtoMessage() {}

func (x *SubjectList) ProtoReflect() protoreflect.Message {
	mi := &file_coursemanagement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectList.ProtoReflect.Descriptor instead.
func (*SubjectList) Descriptor() ([]byte, []int) {
	return file_coursemanagement_proto_rawDescGZIP(), []int{2}
}

func (x *SubjectList) GetSubject() []*SubjectItem {
	if x != nil {
		return x.Subject
	}
	return nil
}

type SubjectId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SubjectId) Reset() {
	*x = SubjectId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coursemanagement_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectId) ProtoMessage() {}

func (x *SubjectId) ProtoReflect() protoreflect.Message {
	mi := &file_coursemanagement_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectId.ProtoReflect.Descriptor instead.
func (*SubjectId) Descriptor() ([]byte, []int) {
	return file_coursemanagement_proto_rawDescGZIP(), []int{3}
}

func (x *SubjectId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_coursemanagement_proto protoreflect.FileDescriptor

var file_coursemanagement_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x47, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x1b, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xf7,
	0x01, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x0a, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x1a, 0x0c, 0x2e,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x2d, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0c,
	0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x0c, 0x2e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x0c, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x1a, 0x0c, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22,
	0x00, 0x12, 0x25, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x0a, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x1a, 0x06,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2d, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coursemanagement_proto_rawDescOnce sync.Once
	file_coursemanagement_proto_rawDescData = file_coursemanagement_proto_rawDesc
)

func file_coursemanagement_proto_rawDescGZIP() []byte {
	file_coursemanagement_proto_rawDescOnce.Do(func() {
		file_coursemanagement_proto_rawDescData = protoimpl.X.CompressGZIP(file_coursemanagement_proto_rawDescData)
	})
	return file_coursemanagement_proto_rawDescData
}

var file_coursemanagement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coursemanagement_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: Empty
	(*SubjectItem)(nil), // 1: SubjectItem
	(*SubjectList)(nil), // 2: SubjectList
	(*SubjectId)(nil),   // 3: SubjectId
}
var file_coursemanagement_proto_depIdxs = []int32{
	1, // 0: SubjectList.subject:type_name -> SubjectItem
	0, // 1: CourseManagementService.GetAllSubject:input_type -> Empty
	3, // 2: CourseManagementService.GetSubject:input_type -> SubjectId
	1, // 3: CourseManagementService.AddNewSubject:input_type -> SubjectItem
	1, // 4: CourseManagementService.UpdateSubjectDetail:input_type -> SubjectItem
	3, // 5: CourseManagementService.DeleteSubject:input_type -> SubjectId
	2, // 6: CourseManagementService.GetAllSubject:output_type -> SubjectList
	1, // 7: CourseManagementService.GetSubject:output_type -> SubjectItem
	1, // 8: CourseManagementService.AddNewSubject:output_type -> SubjectItem
	1, // 9: CourseManagementService.UpdateSubjectDetail:output_type -> SubjectItem
	0, // 10: CourseManagementService.DeleteSubject:output_type -> Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coursemanagement_proto_init() }
func file_coursemanagement_proto_init() {
	if File_coursemanagement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coursemanagement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coursemanagement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coursemanagement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coursemanagement_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coursemanagement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coursemanagement_proto_goTypes,
		DependencyIndexes: file_coursemanagement_proto_depIdxs,
		MessageInfos:      file_coursemanagement_proto_msgTypes,
	}.Build()
	File_coursemanagement_proto = out.File
	file_coursemanagement_proto_rawDesc = nil
	file_coursemanagement_proto_goTypes = nil
	file_coursemanagement_proto_depIdxs = nil
}
