// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: coursemanagement.proto

package course_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CourseManagementServiceClient is the client API for CourseManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseManagementServiceClient interface {
	GetAllCourses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CourseList, error)
	GetCourse(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*CourseItem, error)
	AddNewCourse(ctx context.Context, in *CourseItem, opts ...grpc.CallOption) (*CourseItem, error)
	UpdateCourseDetail(ctx context.Context, in *CourseItem, opts ...grpc.CallOption) (*CourseItem, error)
	DeleteCourse(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*Empty, error)
}

type courseManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseManagementServiceClient(cc grpc.ClientConnInterface) CourseManagementServiceClient {
	return &courseManagementServiceClient{cc}
}

func (c *courseManagementServiceClient) GetAllCourses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CourseList, error) {
	out := new(CourseList)
	err := c.cc.Invoke(ctx, "/course_management.CourseManagementService/GetAllCourses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseManagementServiceClient) GetCourse(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*CourseItem, error) {
	out := new(CourseItem)
	err := c.cc.Invoke(ctx, "/course_management.CourseManagementService/GetCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseManagementServiceClient) AddNewCourse(ctx context.Context, in *CourseItem, opts ...grpc.CallOption) (*CourseItem, error) {
	out := new(CourseItem)
	err := c.cc.Invoke(ctx, "/course_management.CourseManagementService/AddNewCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseManagementServiceClient) UpdateCourseDetail(ctx context.Context, in *CourseItem, opts ...grpc.CallOption) (*CourseItem, error) {
	out := new(CourseItem)
	err := c.cc.Invoke(ctx, "/course_management.CourseManagementService/UpdateCourseDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseManagementServiceClient) DeleteCourse(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/course_management.CourseManagementService/DeleteCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseManagementServiceServer is the server API for CourseManagementService service.
// All implementations must embed UnimplementedCourseManagementServiceServer
// for forward compatibility
type CourseManagementServiceServer interface {
	GetAllCourses(context.Context, *Empty) (*CourseList, error)
	GetCourse(context.Context, *CourseId) (*CourseItem, error)
	AddNewCourse(context.Context, *CourseItem) (*CourseItem, error)
	UpdateCourseDetail(context.Context, *CourseItem) (*CourseItem, error)
	DeleteCourse(context.Context, *CourseId) (*Empty, error)
	mustEmbedUnimplementedCourseManagementServiceServer()
}

// UnimplementedCourseManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCourseManagementServiceServer struct {
}

func (UnimplementedCourseManagementServiceServer) GetAllCourses(context.Context, *Empty) (*CourseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCourses not implemented")
}
func (UnimplementedCourseManagementServiceServer) GetCourse(context.Context, *CourseId) (*CourseItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedCourseManagementServiceServer) AddNewCourse(context.Context, *CourseItem) (*CourseItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewCourse not implemented")
}
func (UnimplementedCourseManagementServiceServer) UpdateCourseDetail(context.Context, *CourseItem) (*CourseItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourseDetail not implemented")
}
func (UnimplementedCourseManagementServiceServer) DeleteCourse(context.Context, *CourseId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourse not implemented")
}
func (UnimplementedCourseManagementServiceServer) mustEmbedUnimplementedCourseManagementServiceServer() {
}

// UnsafeCourseManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseManagementServiceServer will
// result in compilation errors.
type UnsafeCourseManagementServiceServer interface {
	mustEmbedUnimplementedCourseManagementServiceServer()
}

func RegisterCourseManagementServiceServer(s grpc.ServiceRegistrar, srv CourseManagementServiceServer) {
	s.RegisterService(&CourseManagementService_ServiceDesc, srv)
}

func _CourseManagementService_GetAllCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseManagementServiceServer).GetAllCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course_management.CourseManagementService/GetAllCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseManagementServiceServer).GetAllCourses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseManagementService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseManagementServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course_management.CourseManagementService/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseManagementServiceServer).GetCourse(ctx, req.(*CourseId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseManagementService_AddNewCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseManagementServiceServer).AddNewCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course_management.CourseManagementService/AddNewCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseManagementServiceServer).AddNewCourse(ctx, req.(*CourseItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseManagementService_UpdateCourseDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseManagementServiceServer).UpdateCourseDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course_management.CourseManagementService/UpdateCourseDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseManagementServiceServer).UpdateCourseDetail(ctx, req.(*CourseItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseManagementService_DeleteCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseManagementServiceServer).DeleteCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/course_management.CourseManagementService/DeleteCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseManagementServiceServer).DeleteCourse(ctx, req.(*CourseId))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseManagementService_ServiceDesc is the grpc.ServiceDesc for CourseManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course_management.CourseManagementService",
	HandlerType: (*CourseManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllCourses",
			Handler:    _CourseManagementService_GetAllCourses_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _CourseManagementService_GetCourse_Handler,
		},
		{
			MethodName: "AddNewCourse",
			Handler:    _CourseManagementService_AddNewCourse_Handler,
		},
		{
			MethodName: "UpdateCourseDetail",
			Handler:    _CourseManagementService_UpdateCourseDetail_Handler,
		},
		{
			MethodName: "DeleteCourse",
			Handler:    _CourseManagementService_DeleteCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coursemanagement.proto",
}
